### ISSUE TITLE
i tried your medium article but it didnt work

### ISSUE THREAD

**Issue by rockocoop** [ChamilaLiyanage/kafka-keda-example#2]
hey man,  i know its an older article but i tried the procedure and no scaling.  i did notice that my kafka topic offset was not updating with the consumer processing.  Perhaps there is something i missed?

**Comment by oranjjun** [comment]
Hi @rockocoop, there's indeed some minor issues on autoscaling. Maybe you could refer to this [PR](https://github.com/ChamilaLiyanage/kafka-keda-example/pull/3) that I have just raised.

**Comment by ChamilaLiyanage** [comment]
Would be fixed by the PR done by @oranjjun , thank you for the contribution.
